# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cllikProj <- function(x, dims, ALPHA0, BETA0, UU, RR, TAU) {
    .Call('dnc_cllikProj', PACKAGE = 'dnc', x, dims, ALPHA0, BETA0, UU, RR, TAU)
}

cLogLikelihood <- function(Yvec, Xvec, DIMS, ALPHA, SS) {
    .Call('dnc_cLogLikelihood', PACKAGE = 'dnc', Yvec, Xvec, DIMS, ALPHA, SS)
}

cposteriorNoOmega <- function(dims, Yvec, XVec, RR, TAU, SS, ALPHA, BETA, Z, UU, CC, GAMSTAR, A2STAR, B2STAR, B3STAR) {
    .Call('dnc_cposteriorNoOmega', PACKAGE = 'dnc', dims, Yvec, XVec, RR, TAU, SS, ALPHA, BETA, Z, UU, CC, GAMSTAR, A2STAR, B2STAR, B3STAR)
}

csimulateData <- function(Xvec, dims, ALPHA, SS) {
    .Call('dnc_csimulateData', PACKAGE = 'dnc', Xvec, dims, ALPHA, SS)
}

cVBnoClust <- function(dims, Yvec, muVec, SigVec, A2STAR, B2STAR, B3STAR, EOmVec, A0, B0, A0STAR, B0STAR, AI2, BI2, A3, B3, ES, ES2) {
    .Call('dnc_cVBnoClust', PACKAGE = 'dnc', dims, Yvec, muVec, SigVec, A2STAR, B2STAR, B3STAR, EOmVec, A0, B0, A0STAR, B0STAR, AI2, BI2, A3, B3, ES, ES2)
}

cVBUpdate <- function(DIMS, Yvec, CC, GAMSTAR, A2STAR, B2STAR, B3STAR, EOmVec, muVec, SigVec, BI0G, BitbarVec, BithkVec, ER, ER2, AI2, BI2, NU, A3, B3, ES, ES2, GAM) {
    .Call('dnc_cVBUpdate', PACKAGE = 'dnc', DIMS, Yvec, CC, GAMSTAR, A2STAR, B2STAR, B3STAR, EOmVec, muVec, SigVec, BI0G, BitbarVec, BithkVec, ER, ER2, AI2, BI2, NU, A3, B3, ES, ES2, GAM)
}

drawMiss <- function(dims, Yvec, SS, MISS, XVec, ALPHA) {
    .Call('dnc_drawMiss', PACKAGE = 'dnc', dims, Yvec, SS, MISS, XVec, ALPHA)
}

drawS <- function(dims, Yvec, OmVec, XVec, ALPHA) {
    .Call('dnc_drawS', PACKAGE = 'dnc', dims, Yvec, OmVec, XVec, ALPHA)
}

drawTau <- function(dims, Xvec, RR, UU, Z) {
    .Call('dnc_drawTau', PACKAGE = 'dnc', dims, Xvec, RR, UU, Z)
}

drawU <- function(dims, TAU, RR, Xvec, Z) {
    .Call('dnc_drawU', PACKAGE = 'dnc', dims, TAU, RR, Xvec, Z)
}

drawXZar <- function(dims, XVec, Yvec, OmVec, SS, ALPHA, TAU, RR, UU, ZZ, rnVec, BB, RNa, B3Star, CC) {
    .Call('dnc_drawXZar', PACKAGE = 'dnc', dims, XVec, Yvec, OmVec, SS, ALPHA, TAU, RR, UU, ZZ, rnVec, BB, RNa, B3Star, CC)
}

